version: "3.8"
services:
  backend-app:
    build: ./app
    image: backend
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src
    env_file: .env
    command: sh -c './wait-for db:3306 -t 0 -- npm run start'
    depends_on: 
        - db
  db:
    container_name: clnwgn_db
    build: ./db
    image: mysql
    platform: linux/x86_64
    ports:
      - 3309:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretPassword
      MYSQL_DATABASE: CleanWagon
